# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_on',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_on',
            field=models.DateField(null=True),
        ),
    ]
