# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_trip_created_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_user',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_user',
            field=models.ManyToManyField(null=True, related_name='created_trips', to='travel.User'),
        ),
    ]
