# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20171217_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(null=True, related_name='trips', to='travel.User'),
        ),
    ]
