# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20171217_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_user',
        ),
        migrations.AddField(
            model_name='trip',
            name='created_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_trips', to='travel.User'),
        ),
    ]
